version: "3.9"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db 
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-ylp0ug64gh*g!v!4%+q@b7s-&7h7r3s7g8wv$$d+$$3%$$9e5yfek"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
